spring:
  application:
    name: mock-api-rest
  datasource:
    url: jdbc:mysql://localhost:3306/db_mock
    username: dev
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        package-to-scan: com.magtechnologies.fakeapius.infrastructure.entities
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# Configuração do SpringDoc
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  show-actuator: true